image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: git clone https://github.com/emscripten-core/emsdk.gitn                  &&
          cd emsdk                                                                 &&
          ./emsdk install latest                                                   &&
          ./emsdk activate latest                                                  &&
          source ./emsdk_env.sh                                                    
    
