image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: git clone https://github.com/emscripten-core/emsdk.git                                                  &&
          cd emsdk                                                                                                &&
          ./emsdk install latest                                                                                  &&
          ./emsdk activate latest                                                                                 &&
          source ./emsdk_env.sh                                                                                   &&
          mkdir myExample                                                                                         &&
          cd myExample                                                                                            &&
          echo -e "#include <stdio.h>\n\nint main() {\n   printf(\"Hello World\");\n  return 0;\n}" > mytest.c     && 
          emcc mytest.c -o mytext.html                                                                            &&  
          echo $PATH                                                                                              &&
          echo "Emscripten Help Files"                                                                            &&
          echo ""                                                                                                 &&
          ./emsdk help                                                                                            &&
          echo "em++ Help Files"                                                                                  &&
          em++ --help                                                                                             &&
          echo "emcc help files"                                                                                  &&
          emcc --help                                           
    
