image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: git clone https://github.com/emscripten-core/emsdk.git                   &&
          cd emsdk                                                                 &&
          ./emsdk install latest                                                   &&
          ./emsdk activate latest                                                  &&
          source ./emsdk_env.sh                                                    &&
          ln -s ./upstream/emscripten/emcc myemcc                                  &&
          ln -s ./upstream/emscripten/em++ myem++                                  &&
          ./emsdk help                                                             
    
